// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.2.0
// Project name: SquareLine_Project_QVGA

#ifndef _SQUARELINE_PROJECT_QVGA_UI_H
#define _SQUARELINE_PROJECT_QVGA_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include <lvgl.h>

#include "ui_events.h"
extern lv_obj_t * ui_Screen1;
extern lv_obj_t* ui_Label1;
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
