// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.2.0
// Project name: SquareLine_Project_QVGA

#include "ui.h"

void RequestEngineStatus_CB(lv_event_t * e)
{
	// Your code here
}

void RequestBatteryStatus_CB(lv_event_t * e)
{
	// Your code here
}

void RequestTempStatus_CB(lv_event_t * e)
{
	// Your code here
}
